name: level-5 artifacts

on:
    workflow_dispatch:

    pull_request:
        types: [opened, edited]
        branches:
            - main

    push:
        branches:
            - main
            - 'dev-*'
            - 'feat/**'
        paths-ignore: '.github/workflows/*'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: set up deno runtime
              uses: denoland/setup-deno@v1
              with:
                  deno-version: v1.x

            - name: checkout source code
              uses: actions/checkout@v4

            - name: run tests + coverage
              run: 'deno test --coverage=tests/coverage'

            - name: generate HTML output for coverage
              run: deno coverage tests/coverage --html

    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: deploy to VPS
              run: echo "deployed ..."
